name: LocalStack CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:2.2.0
        ports:
          - "4566:4566"
          - "4510-4559:4510-4559"
        options: >-
          --env SERVICES=s3,sqs,lambda
          --env DEFAULT_REGION=ap-southeast-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Terraform Docker Image
        run: |
          docker build --tag local/terraform:1.5 -f ./Dockerfile .

      - name: Wait for LocalStack to start
        run: |
          for i in {1..30}; do  # Adjusted retries to 30
            if curl -s http://localhost:4566/health | grep '"s3": "available"'; then
              echo "LocalStack is running"
              break
            fi
            echo "Waiting for LocalStack to start..."
            sleep 2
          done

      - name: Check LocalStack Health
        run: curl -s http://localhost:4566/health

      - name: Create S3 Bucket
        run: |
          aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket --debug || echo "Failed to create bucket"

      - name: Show LocalStack Logs
        run: docker logs localstack

      - name: List S3 Buckets
        run: |
          aws --endpoint-url=http://localhost:4566 s3 ls
