name: LocalStack Terraform CI

on: [push, pull_request]

jobs:
  your_job:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --network-alias localstack
        env:
          SERVICES: "lambda,s3,sts"

    steps:
      - name: Check LocalStack Status
        run: |
          curl -s http://localstack:4566/health || echo "LocalStack is not running"

      - name: Wait for LocalStack
        run: |
          for i in {1..10}; do
            curl -s http://localstack:4566/health | grep '"running": true' && break || sleep 2
          done

      - name: Get Caller Identity (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"       # Dummy access key
          AWS_SECRET_ACCESS_KEY: "test"     # Dummy secret key
        run: |
          aws --endpoint-url=http://localstack:4566 --region ap-southeast-1 sts get-caller-identity
