name: CI Pipeline

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: "lambda,s3,sts"
          DEFAULT_REGION: "ap-southeast-1"

    steps:
      - name: Wait for LocalStack to be ready
        run: |
          for i in {1..30}; do
            health_status=$(curl -s http://localhost:4566/health)
            echo "Health status: $health_status"
            if [[ $health_status == *'"running": true'* ]]; then
              echo "LocalStack is ready!"
              break
            fi
            echo "Waiting for LocalStack to start..."
            sleep 2
          done

      - name: Get LocalStack IP Address
        id: get_localstack_ip
        run: |
          for i in {1..10}; do
            localstack_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' localstack) && echo "::set-output name=ip::$localstack_ip" && break || (echo "LocalStack not ready, retrying..." && sleep 2)
          done

      - name: Get Caller Identity (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
        run: |
          localstack_ip=${{ steps.get_localstack_ip.outputs.ip }}
          echo "LocalStack IP: $localstack_ip"
          if [[ -z "$localstack_ip" ]]; then
            echo "LocalStack IP not found, exiting..."
            exit 1
          fi
          for i in {1..5}; do
            aws --endpoint-url=http://$localstack_ip:4566 --region ap-southeast-1 sts get-caller-identity && break || (echo "Retrying..." && sleep 2)
          done
