name: CI Pipeline

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: "lambda,s3,sts"
          DEFAULT_REGION: "ap-southeast-1"
        options: >-
          --health-cmd='curl -f http://localhost:4566/health || exit 1'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --restart=always
          --stop-timeout=300s

    steps:
      - name: Wait for LocalStack to be ready
        run: |
          for i in {1..5}; do
            health_status=$(curl -s http://localhost:4566/health)
            echo "Health status: $health_status"
            if [[ $health_status == *'"running": true'* ]]; then
              echo "LocalStack is ready!"
              break
            fi
            echo "Waiting for LocalStack to start..."
            sleep 2
          done

      # Sleep for a few seconds to ensure LocalStack has started
      - name: Wait for LocalStack to initialize
        run: |
          echo "Waiting an additional 10 seconds for LocalStack to initialize..."
          sleep 10

      - name: Get LocalStack IP Address
        id: get_localstack_ip
        run: |
          for i in {1..5}; do
            localstack_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' localstack) && echo "::set-output name=ip::$localstack_ip" && break || (echo "LocalStack not ready, retrying..." && sleep 2)
          done

      - name: Get Caller Identity (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
        run: |
          localstack_ip=${{ steps.get_localstack_ip.outputs.ip }}
          echo "LocalStack IP: $localstack_ip"
          if [[ -z "$localstack_ip" ]]; then
            echo "LocalStack IP not found, exiting..."
            exit 1
          fi
          for i in {1..5}; do
            aws --endpoint-url=http://$localstack_ip:4566 --region ap-southeast-1 sts get-caller-identity && break || (echo "Retrying..." && sleep 2)
          done

      # Sleep for 2400 seconds (40 minutes) in the same stage
      - name: Sleep for 40 minutes
        run: |
          echo "Sleeping for 2400 seconds (40 minutes)..."
          sleep 2400

      - name: Check Caller Identity After Sleep (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
        run: |
          localstack_ip=${{ steps.get_localstack_ip.outputs.ip }}
          echo "LocalStack IP: $localstack_ip"
          if [[ -z "$localstack_ip" ]]; then
            echo "LocalStack IP not found, exiting..."
            exit 1
          fi
          for i in {1..5}; do
            aws --endpoint-url=http://$localstack_ip:4566 --region ap-southeast-1 sts get-caller-identity && break || (echo "Retrying..." && sleep 2)
          done

      # Add any other steps you need to run after checking caller identity
