name: CI Pipeline

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --network-alias localstack
        env:
          SERVICES: "lambda,s3,sts"

    steps:
      - name: Check LocalStack Health
        run: |
          for i in {1..10}; do
            if curl -s http://localstack:4566/health | grep '"running": true'; then
              echo "LocalStack is running."
              break
            else
              echo "Waiting for LocalStack to start..."
              sleep 2
            fi
          done

      - name: Get Caller Identity (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"       # Dummy access key
          AWS_SECRET_ACCESS_KEY: "test"     # Dummy secret key
        run: |
          aws --endpoint-url=http://localstack:4566 --region ap-southeast-1 sts get-caller-identity
