name: CI Pipeline

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --network-alias localstack
        env:
          SERVICES: "lambda,s3,sts"
          DEFAULT_REGION: "ap-southeast-1"

    steps:
      - name: Wait for LocalStack to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localstack:4566/health | grep '"running": true' && break || echo "Waiting for LocalStack to start..." && sleep 2
          done

      - name: Get Caller Identity (LocalStack)
        env:
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
        run: |
          localstack_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' localstack)
          echo "LocalStack IP: $localstack_ip"
          for i in {1..5}; do
            aws --endpoint-url=http://$localstack_ip:4566 --region ap-southeast-1 sts get-caller-identity && break || (echo "Retrying..." && sleep 2)
          done
